version: '3'
name: measure-reader
services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    networks:
      - measure-reader
  back-end:
    container_name: back-end
    build:
      context: .
    env_file:
      - .env
    image: measure-register/backend
    ports:
      - '80:80'
    depends_on:
      - database
    logging:
      options:
        max-size: '1g'
        max-file: '3'
    networks:
      - measure-reader
networks:
  measure-reader:
    driver: bridge
